### ISSUE TITLE
Customize labels

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#4]
Labels should be customize since default labels are not clear enough for describing the issues: 
- Please be careful while choosing the colors, there should not be duplicate color if possible
- Nor too many neither too few labels will not be helpful

Useful Links:

- [github label example](https://seantrane.com/posts/logical-colorful-github-labels-18230/)
- [simple one](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)
- [tutorial](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels)

Due date: 07.03.2022
Revisor: @mervegrbz

**Comment by mervegrbz** [comment]
@rburaksaritas  Can you do this issue? It is a bit urgent since we started using issues :)

**Comment by rburaksaritas** [comment]
Sure, I'm on it.

**Comment by rburaksaritas** [comment]
@mervegrbz how is the current label set? I grouped each label of prefix type with different shades of same color so that they look more organized. I can always add more, based on the feedback and requirements.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/86561984/222905800-246ee8a3-f062-443d-b79f-7a461d571f2f.png">
