### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#45]
Mock ups for the admin should be done.

Deadline: 24.03.23
Reviewer: @bgmrsln

**Comment by Sahin-Albayram** [comment]
@bgmrsln  can you review page pls ? What should I add or this pages enough ?

https://app.diagrams.net/?src=about#Hbounswe%2Fbounswe2023group2%2Fmain%2Fmockups%2FAdminPageMockup.drawio

**Comment by bgmrsln** [comment]
Should there be a ban user button? I only saw cancel verification and delete action.

**Comment by bgmrsln** [comment]
Also it would be better if you could add some actual data inside the tables.

**Comment by Sahin-Albayram** [comment]
> Should there be a ban user button? I only saw cancel verification and delete action.

I will add, but actually, I do not like authenticated/verified user requirements because users who are not authenticated or verified are only able to view the platform. What will banning achieve in this case? Can we completely prevent someone from viewing the platform since people can view it without logging into any account? Although we can ban suspect profiles, new profiles can easily be created. If you can clarify the concept of "banning" and the difference between canceling verification, I would be happy.
