### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#48]
System requirements for the profile page should be written.

**Comment by mehmetkuzu** [comment]
A question: Will write the system requirements for Profiles but have you checked the section under functional requirements when moving forward to second draft. Because the effort will be wasted if these are cleared later. 

I will also update the mockup for profile according to these.

This part:
  * 1.1.2.3 Users shall be able to select which details of their profile information will be publicly displayed.
  * 1.1.2.5 Users' profile information will be subject to verification, correction, and deletion by users having the rights to do.
  * 1.1.2.6 Users shall be designated to operational roles by users having the rights to do so.
  * 1.1.2.7 Users shall be able to confirm or reject the operational roles they are designated.
  * 1.1.2.8 Users shall be able to propose themselves as active resources (within available time limits) according to their profile information.

**Comment by mehmetkuzu** [comment]
System requirements for Profile is done.

**Comment by mehmetkuzu** [comment]
I see.
For 1.1.2.3. shall is not a problem. It is not "Users shall select". They will be able to select. 
We can put it this way:
Users shall be able to select the parts of their profile which will not be publicly displayed.
For1.1.2.5. we can:
Users with necessary authorization shall be able update and delete parts of other users profile information.
Users with necessary authorization shall be able to suggest system level operational roles (which are attributes of user profiles) to other users.
Users shall be able to confirm or reject system level operational roles suggested for them.

**Comment by bgmrsln** [comment]
I still dont think they are clear, can a user can chose to not display their name? Maybe it is for later, which data is subject to this. 
1.1.2.5. deleting and updating other users data? I dont think this should be a requirement. Admin will have banning other than that how would we use this? 
1.1.2.7. is better this way I think
I am not sure if this accepting or rejecting is a simple mission for simplicity. how about when someone is suggested we just send the notification and leave the rest to the user. I am saying this because I know many groups from last years had to give up on their requirements so I believe simple is better.

**Comment by mehmetkuzu** [comment]
Ok.
(So a user will not be able to hide his/her data from public without hiding it from the system.)

**Comment by mehmetkuzu** [comment]
Updated.

**Comment by bgmrsln** [comment]
No, I mean we should point out which data should be hidden maybe? Maybe they can hide their phone number, they can only make it visible when they enter a need or resource and click on show my number?

**Comment by mehmetkuzu** [comment]
Ok.
How about putting a switch on "pages" of the profile.
(After grouping information of the profile)
So default is "public" but the user can change it.
(I can propose a list of the parts of the profile which can be hidden)
Something like that:
<img width="541" alt="Screenshot 2023-03-21 at 12 49 28" src="https://user-images.githubusercontent.com/46297916/226570663-063f708a-ad86-4b08-98ab-48075134acdb.png">

**Comment by mehmetkuzu** [comment]
I will review the section in the SRS  for that.
