### ISSUE TITLE
Mobile -Action implementation

### ISSUE THREAD

**Issue by HasanBingolbali** [bounswe/bounswe2023group2#669]
### Issue Description

I will implement actions including matching need and resources and deleting them. It must be consistent with overall design

### Deadline of the Issue

12.12.2023

### Reviewer

Halil İbrahim Gürbüz

**Comment by egecans** [comment]
We changed the issues as I explained in #735

**Comment by egecans** [comment]
This issue is cancelled since we had no time before the demo and it was already handled in the frontend. Revising the app (#797) and fixing the bugs was more valuable than a thing that is proved in the frontend. 
You can see some of details of the actions from our app. But you can't create them without giving need id hardcoded way. We may implement it in winter-break to develop our app more.
